name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GO_VERSION: '1.25.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run unit tests
        run: go test ./...

      - name: Download wasm module
        run: make wasm

      - name: Build Go binaries
        run: make go

      - name: Create GitHub release
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          mapfile -t files < <(find dist -type f -print)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No build artifacts found under dist/" >&2
            exit 1
          fi
          gh release create "${TAG_NAME}" \
            --title "${TAG_NAME}" \
            --generate-notes \
            "${files[@]}"
